version: '2'

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - gocritic

formatters:
  enable:
    - gofmt
